### ISSUE TITLE
Not able to build

### ISSUE THREAD

**Issue by sangeeta0201** [SaswatPadhi/LoopInvGen#1]
I am getting an error while building re2 which is required by core_extended.

```
=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ERROR] The compilation of re2 failed at "make".

```

Also running command 
```
 opam install 4.06.0+flambda
[ERROR] No package named 4 found.
```

I am trying ocaml for the first time. I know this is not directly related to your project but any help would be much appreciated.

**Comment by SaswatPadhi** [comment]
Thanks for the report!

There are two issues here:
- The first one is now fixed with the commit above -- the right command to install an OCaml compiler version using `opam` is `opam switch <version>`, not `opam install <version>`.
- The `re2` compilation failure is most likely due to `m4` or `g++` missing on your system. You could check with `opam depext re2`. Try installing both these packages and an `opam install re2` again. (After you've `opam switch`ed to OCaml >= `4.06.0+lambda`).

**Comment by sangeeta0201** [comment]
Thank you Saswat. I am able to build now.
