### ISSUE TITLE
Inquiry about how LoopInvGen works

### ISSUE THREAD

**Issue by riceluxs1t** [SaswatPadhi/LoopInvGen#8]
Hi Saswat Padhi, I am presenting for my school project about LoopInvGen because I am interested in the SyGus competition. I got to play with LoopInvGen against a few code snippets. One particular code snippet LoopInvGen failed to correctly produce an invariant is the following program (expressed in terms of Dafny syntax).

https://gist.github.com/riceluxs1t/3864412a8ce7f9d5ffa7c1f38fde8291

The function does integer division of x/y and returns its quotient and remainder.

I translated it to the below v1 SyGus format

`(set-logic LIA)

(synth-inv inv-f ((x Int) (y Int) (q Int) (r Int)))

(declare-primed-var x Int)
(declare-primed-var y Int)
(declare-primed-var q Int)
(declare-primed-var r Int)

(define-fun pre-f ((x Int) (y Int) (q Int) (r Int)) Bool
(and
  (> y 0)
  (>= x 0)
  (= q 0)
  (= r x))
)

(define-fun trans-f ((x Int) (y Int) (q Int) (r Int) (x! Int) (y! Int) (q! Int) (r! Int)) Bool
(and
  (>= r y)
  (= y! y)
  (= x! x)
  (= r! (- r y))
  (= q! (+ q 1))
))

(define-fun post-f ((x Int) (y Int) (q Int) (r Int)) Bool
(or
 (>= r y)
 (and
    (= x (+ r (* q y)))
    (>= r 0)
;    (< r y)
 )
))

(inv-constraint inv-f pre-f trans-f post-f)

(check-synth)`

I believe the encoding is correct but am trying to debug why LoopInvGen would fail to synthesize correctly for this example. It currently times out after a while. If you spot anything obvious, please let me know.

**Comment by SaswatPadhi** [comment]
Hi @riceluxs1t 

Thanks for the report. This was due to two issues:
1. There was a typo in the `loopinvgen.sh` script introduced in a recent commit.
2. The invariant (and postcondition) in your case are actually non-linear, so you should use `(set-logic NIA)` instead of LIA.

Please pull the latest changes and try rebuilding LoopInvGen and running your example. On my machine, it is able to solve the case.

I have also added this test case in [benchmarks/NIA/others/issue_8.sl](../tree/master/benchmarks/NIA/other/issue_8.sl).

Please feel free to reopen this issue if this does not work at your end.

**Comment by riceluxs1t** [comment]
Sweet. Glad that it is able to synthesize it correctly. Please update the remote docker image.

**Comment by SaswatPadhi** [comment]
Unfortunately builds on docker hub are super slow :(

This should show `passed` instead of `building` when the build is complete: ![](https://camo.githubusercontent.com/65e8566393fb53e7232ed88e8f9f9b57ab041e09/68747470733a2f2f696d672e736869656c64732e696f2f646f636b65722f636c6f75642f6275696c642f70616468692f6c6f6f70696e7667656e2e7376673f6c6f676f3d646f636b6572267374796c653d706f706f7574266c6162656c3d446f636b65722b496d616765)
